databases:
  - name: huyuhoy-postgres
    plan: free
    databaseName: huyuhoydb
    user: huyuhoy

services:
  - type: web
    name: huyuhoy-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py seed_meals && python manage.py collectstatic --noinput
    startCommand: gunicorn huyuhoy.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: huyuhoy-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: huyuhoy-postgres
          property: connectionString
      - key: FRONTEND_URL
        value: https://huyuhoy-frontend.onrender.com
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: SESSION_COOKIE_SAMESITE
        value: None
      - key: CSRF_COOKIE_SAMESITE
        value: None
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "True"
      - key: SECURE_HSTS_PRELOAD
        value: "True"
