# Generated by Django 6.0.3 on 2026-03-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
