# Generated by Django 4.2.5 on 2023-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('withRice', models.DecimalField(decimal_places=2, max_digits=2)),
                ('withOutRice', models.DecimalField(decimal_places=2, max_digits=2)),
                ('pImage', models.ImageField(upload_to='meal_images/')),
            ],
        ),
    ]
