# Generated by Django 4.2.6 on 2023-10-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
