# Generated by Django 4.2.7 on 2025-12-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('food', '0003_create_acceptrefuseorder_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='rice',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='drinks',
            field=models.CharField(choices=[('None', 'None'), ('Sprite', 'Sprite'), ('Coke', 'Coke'), ('Mountain Dew', 'Mountain Dew')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unlirice',
            field=models.BooleanField(default=False, verbose_name='Unlimited Rice'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('GCASH', 'GCash'), ('CASH', 'Cash')], default='Cash', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_num',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
