# Generated by Django 4.2.6 on 2023-11-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_address_order_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ref_num', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('GCASH', 'GCash'), ('CASH', 'Cash')], default='Cash', max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Pickup', 'Pickup')], default='Pickup', max_length=10),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='food.order'),
        ),
    ]
