# Generated by Django 4.2.6 on 2023-11-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_payment_remove_order_shipping_address_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='food.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_num',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
    ]
