# Generated by Django 4.2.6 on 2023-11-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_payment_remove_order_shipping_address_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref_num',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
