# Generated by Django 4.2.6 on 2023-11-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_payment_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_number',
        ),
    ]
